
```{r }
####################################################################
###################    4.1 Getting started    ######################
####################################################################

options(warn=-1)

```
```{r 4.1.1 Installing packages}
if(FALSE){
  install.packages("sf")
  install.packages("tools")
  install.packages("ggpubr")
  install.packages("dplyr")
  install.packages("ggplot2")
}

install.packages("sandwichr")


```
```{r 4.1.2 Importing packages}
library(sandwichr)
library(ggplot2)
library(sf)
library(tools)
library(ggpubr)
library(dplyr)


## Initializing the generator for pseudo random numbers
set.seed(0)


####################################################################
#####################    4.2 Case study 1    #######################
####################################################################

```
```{r 4.2.1 Loading data}
hs.sampling.name <- system.file("extdata", "hs.sampling.shapefile.shp",
                                package="sandwichr")
hs.ssh.name <- system.file("extdata", "hs.ssh.shapefile.shp",
                           package="sandwichr")
hs.reporting.name <- system.file("extdata", "hs.reporting.shapefile.shp",
                                 package="sandwichr")
hs.sampling.name
hs.ssh.name
hs.reporting.name

hs.data <- load.data.shp(sampling.file=hs.sampling.name,
                         ssh.file=hs.ssh.name,
                         reporting.file=hs.reporting.name)
# Sampling
head(hs.data[[1]])
class(hs.data[[1]])
attributes(hs.data[[1]])
summary(hs.data[[1]])

# SSH
head(hs.data[[2]])
class(hs.data[[2]])
attributes(hs.data[[2]])
summary(hs.data[[2]])

# Reporting
head(hs.data[[3]])
class(hs.data[[3]])
attributes(hs.data[[3]])
summary(hs.data[[3]])

# Visualizing data inputs (Figure 5)
pre_legend_title = expression(atop(bold("Sampling Units"),
                                   "\nHuman Population Density\n(Person Per Square Mile)"))

ggplot() +
  geom_sf(data=hs.data[[2]], 
          fill="#FAFAFA", 
          colour="#B2B2B2") + 
  geom_sf(data=hs.data[[1]], 
          aes(colour=Population)) +
  scale_color_gradient(low="#E5D5F2",
                       high="#5D2C70",
                       breaks=c(100,200,300,400),
                       labels=c("<100","100-199","200-299",">=300"),
                       guide=guide_legend(title="Sampling Units\nHuman Population Density\n(Person Per Square Mile)",override.aes=list(shape=c(20,20)))) +
  coord_sf(crs=st_crs(4283)) +
  theme_void()+
  theme(
    legend.key.size=unit(0.5,'cm'),
    legend.justification=c(0,1),
    legend.position=c(0.2,0.3),
    legend.spacing.x=unit(0,'cm'),
    text=element_text(family="Futura-Medium"),
    legend.title=element_text(family="Futura-Bold", size=10),
    legend.text=element_text(family="Futura-Medium", size=10)
  )


```
```{r 4.2.2 Selecting SSH layers(s)}
# Inputing another candidate SSH layer for demonstration
hs.ssh2.name <- system.file("extdata", "hs.ssh2.shapefile.shp",
                            package="sandwichr")
hs.ssh2 <- read_sf(dsn=dirname(hs.ssh2.name),
                   layer=file_path_sans_ext(basename(hs.ssh2.name)))
head(hs.ssh2)

# Preparing the SSH layer(s) for evaluation
hs.join <- ssh.data.shp(object=hs.data[[1]], ssh.lyr=hs.data[[2]], ssh.id="STR_1")
hs.join <- ssh.data.shp(object=hs.join, ssh.lyr=hs.ssh2, ssh.id="STR_2")
head(hs.join)

# Calculating the geographical detector q-statistic
ssh.test(object=hs.join, y="Population", x=c("STR_1", "STR_2"), test="factor")

# Calculating the interaction detector
ssh.test(object=hs.join, y="Population", x=c("STR_1", "STR_2"), test="interaction")


```
```{r 4.2.3 Running the Sandwich model}
# Perform the SSH based spatial interpolation
hs.sw <- sandwich.model(object=hs.data, sampling.attr="Population", type="shp")
head(hs.sw$object)
summary(hs.sw)

sf::st_write(obj=hs.sw$object, dsn="hs.sw.shp")

# Calculating the confidence intervals of the interpolation estimates
hs.sw.ci <- sandwich.ci(object=hs.sw, level=.95)
head(hs.sw.ci$object$object)
summary(hs.sw.ci)

sf::st_write(obj=hs.sw.ci$object$object, dsn="hs.sw.ci.shp")

# Plotting (Figures 6 and 7)
ggplot2::autoplot(object=hs.sw)
ggplot2::autoplot(object=hs.sw.ci)


```
```{r 4.2.4 Model validation}
hs.cv <- sandwich.cv(object=hs.data, sampling.attr="Population", k=5, type="shp")
hs.cv


####################################################################
#####################    4.3 Case study 2    #######################
####################################################################

```
```{r 4.3.1 Loading data}
bc.sampling_ssh.name <- system.file("extdata", "bc_sampling_ssh.csv",
                                    package="sandwichr")
bc.reporting_ssh.name <- system.file("extdata", "bc_reporting_ssh.csv",
                                     package="sandwichr")
bc.sampling_ssh.name
bc.reporting_ssh.name

bc.data <- load.data.txt(sampling_ssh.file=bc.sampling_ssh.name,
                         reporting_ssh.file=bc.reporting_ssh.name)

# Sampling-SSH
head(bc.data[[1]])    
class(bc.data[[1]])
summary(bc.data[[1]])

# Reporting-SSH
head(bc.data[[2]])    
class(bc.data[[2]])
summary(bc.data[[2]])

```
```{r 4.3.2 Selecting SSH layers(s)}
bc.join <- ssh.data.txt(object=bc.data)
head(bc.join)

# Calculating the geographical detector q-statistic
ssh.test(object=bc.join, y="Incidence", x="SSHID", test="factor", type="txt")

# Visualizing urban-rural disparities (Figure 8b)
p <- ggerrorplot(bc.data[[1]], x="SSHID", y="Incidence",
                desc_stat="mean_sd", color="black",
                add="violin", add.params=list(color = "darkgray"))

p + scale_x_discrete(labels=c("1"="Urban", "2"="Rural")) +
  theme(axis.title.x=element_blank()) + labs(y="Breast Cancer Incidence\n(Rate per 100,000)")

bc.data[[1]] %>%
  group_by(SSHID) %>%
  summarise_at(vars(Incidence),
               list(name = mean))


```
```{r 4.3.3 Running the model}
# Performing the SSH based spatial interpolation
bc.sw <- sandwich.model(object=bc.data, sampling.attr="Incidence", type="txt",
                        ssh.id.col="SSHID", ssh.weights=list(c(1,2), c("W1","W2")))
head(bc.sw$object)
summary(bc.sw)

write.csv(x=bc.sw$object, file="bc.sw.csv")

# Calculating the confidence intervals of the interpolation estimates
bc.sw.ci <- sandwich.ci(object=bc.sw, level=.95)
head(bc.sw.ci$object$object)
summary(bc.sw.ci)

write.csv(x=bc.sw.ci$object$object, file="bc.sw.ci.csv")

```
```{r 4.3.4 Model validation}
bc.cv <- sandwich.cv(object=bc.data, sampling.attr="Incidence", k=5, type="txt",
                     ssh.id.col="SSHID", reporting.id.col="GBCODE",
                     ssh.weights=list(c(1,2), c("W1","W2")))
bc.cv


# knitr::spin("code.R")
```

